"""initial migration

Revision ID: ab5a531cf240
Revises:
Create Date: 2026-01-13 14:36:10.077216

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "ab5a531cf240"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.String(length=32), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("winner_team", sa.String(length=10), nullable=True),
        sa.Column("players", mysql.JSON(), nullable=True),
        sa.Column("replay_data", mysql.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_number", sa.String(length=10), nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rooms_room_number"), ["room_number"], unique=True)

    op.create_table(
        "game_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("phase", sa.String(length=20), nullable=True),
        sa.Column("round_num", sa.Integer(), nullable=True),
        sa.Column("vote_track", sa.Integer(), nullable=True),
        sa.Column("leader_idx", sa.Integer(), nullable=True),
        sa.Column("current_team", mysql.JSON(), nullable=True),
        sa.Column("quest_results", mysql.JSON(), nullable=True),
        sa.Column("roles_config", mysql.JSON(), nullable=True),
        sa.Column("players", mysql.JSON(), nullable=True),
        sa.Column("votes", mysql.JSON(), nullable=True),
        sa.Column("quest_votes", mysql.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("openid", sa.String(length=64), nullable=False),
        sa.Column("nickname", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("total_games", sa.Integer(), nullable=True),
        sa.Column("wins_good", sa.Integer(), nullable=True),
        sa.Column("wins_evil", sa.Integer(), nullable=True),
        sa.Column("current_room_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["current_room_id"],
            ["rooms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_openid"), ["openid"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_openid"))

    op.drop_table("users")
    op.drop_table("game_states")
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rooms_room_number"))

    op.drop_table("rooms")
    op.drop_table("game_history")
    # ### end Alembic commands ###
